# Generated by Django 5.1.6 on 2025-03-23 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('student', 'Student'), ('tutor', 'Tutor')], max_length=20),
        ),
        migrations.AlterField(
            model_name='tutorprofile',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
