# Generated by Django 5.1.6 on 2025-03-23 16:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_customuser_user_type_alter_tutorprofile_bio'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college_name', models.CharField(blank=True, max_length=255, null=True)),
                ('degree', models.CharField(blank=True, max_length=255, null=True)),
                ('graduation_year', models.IntegerField(blank=True, null=True)),
                ('area_of_interest', models.CharField(blank=True, choices=[('programming', 'Programming'), ('machine_learning', 'Machine Learning'), ('networking', 'Networking'), ('data_science', 'Data Science'), ('app_development', 'App Development'), ('cybersecurity', 'Cybersecurity')], max_length=255, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
