# Generated by Django 5.1.6 on 2025-03-23 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_studentprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='graduation_year',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
