# Generated by Django 5.1.6 on 2025-03-24 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_studentprofile_graduation_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='is_premium',
            field=models.BooleanField(default=False),
        ),
    ]
