# Generated by Django 5.1.6 on 2025-03-25 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_payment_created_at_remove_payment_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile_pics/default.png', null=True, upload_to='profile_pics/'),
        ),
    ]
